name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.0
  firebase_core: ^3.11.0
  http: ^1.3.0
  intl: ^0.20.2
  geolocator: ^13.0.2
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - env/
    - env/youtube_api.json
    - env/news_api.json
    - env/Maps_api.json
    - env/backend_api.json
